export const queryKeys = {
  activities: ['activities'] as const,
  health: (days: number, date?: string) => ['health', days, date ?? 'today'] as const,
  bodyComposition: (days?: number | 'all') => ['body-composition', days ?? 'all'] as const,
  goals: ['goals'] as const,
  goalAchievements: (limit?: number) => ['goals', 'achievements', limit ?? 20] as const,
  plannedSessions: ['planned-sessions'] as const,
  brickAnalysis: (groupId: string) => ['brick-analysis', groupId] as const,
  activityStream: (id: string) => ['activity-stream', id] as const,
  multisportStreams: (id: string) => ['multisport-streams', id] as const,
  physicalNotes: ['physical-notes'] as const,
  coachContext: ['coach-context'] as const,
  coachMemory: ['coach-memory'] as const,
  travelContext: ['travel-context'] as const,
  googleEvents: (from: string, to: string) => ['google-events', from, to] as const,
  googleCalendars: ['google-calendars'] as const,
  conversations: ['conversations'] as const,
  conversation: (id: string) => ['conversation', id] as const,
  dailyBriefing: (date: string) => ['daily-briefing', date] as const,
  weeklyReview: (date: string) => ['weekly-review', date] as const,
  records: ['records'] as const,
  trainingPlan: ['training-plan'] as const,
  thresholdHistory: ['threshold-history'] as const,
  thresholdPreview: ['threshold-preview'] as const,
  athleteProfile: ['athlete-profile'] as const,
  athleteSnapshot: (trainingDayId: string) => ['athlete-snapshot', trainingDayId] as const,
  today: (trainingDayId: string) => ['today', trainingDayId] as const,
  presentationToday: (trainingDayId: string) => ['presentation', 'today', trainingDayId] as const,
  wellnessCheckin: (trainingDayId: string) => ['wellness-checkin', trainingDayId] as const,
  plannedSessionPresentation: (sessionId: string) =>
    ['presentation', 'planned-session', sessionId] as const,
  sessionRationale: (sessionId: string) =>
    ['presentation', 'session-rationale', sessionId] as const,
  weeklyCoachingBrief: (weekStart: string) =>
    ['presentation', 'weekly-coaching-brief', weekStart] as const,
};
