export const approvalCardCopy = {
  title: 'Validation requise',
  approve: 'Valider',
  reject: 'Refuser',
  submit: 'Envoyer la réponse',
  requestChanges: 'Demander une modification',
  customPlaceholder: 'Autre réponse…',
  dismiss: 'Fermer',
  previousQuestion: 'Question précédente',
  nextQuestion: 'Question suivante',
  submitResponse: 'Envoyer la réponse',
  questionProgress: (current: number, total: number) => `Question ${current} sur ${total}`,
  stepAnnouncement: (current: number, total: number) => `Question ${current} sur ${total}`,
  statusAnnouncement: (label: string) => `Statut : ${label}`,
  keyboardHint: 'Entrée pour valider, Échap pour refuser',
  status: {
    submitting: 'Envoi…',
    approved: 'Validé',
    rejected: 'Refusé',
    changesRequested: 'Modification demandée',
    answered: 'Réponse envoyée',
    inputRequired: 'Réponse attendue',
    pending: 'En attente',
  },
} as const;
